services:
  cogna-fe:
    build: .
    container_name: cogna-fe
    ports:
      - "3000:3000"
    environment:
      - API_ROOT=http://cogna-be:8000
      - CLIENT_API_ROOT=http://localhost:8000
    networks:
      - cogna-be_default
    restart: unless-stopped

networks:
  cogna-be_default:
    external: true
